spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/jwtrefresh
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update